[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
hlbc = "0.7"
hlbc-decompiler = "0.7"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
toml = "0.8"
sha2 = "0.10"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
