[package]
name = "mosa"
description = "Mosa Lina modding CLI"
edition.workspace = true
version.workspace = true

[dependencies]
mosa-bc = { path = "../mosa-bc" }
hlbc.workspace = true
hlbc-decompiler.workspace = true
anyhow.workspace = true
clap.workspace = true
mosa-mods = { path = "../mosa-mods" }
toml.workspace = true
sha2.workspace = true
